name: Test SSH Connection Digital Ocean

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
  run: |
    mkdir -p ~/.ssh
    echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -H 134.199.163.224 >> ~/.ssh/known_hosts

- name: Test SSH
  run: |
    ssh -i ~/.ssh/id_rsa root@134.199.163.224 "echo OK"
